baseURL = 'https://rwlpf.github.io/'
languageCode = 'en-gb'
title = 'SQL Bob Scot Blog'
theme='ananke'

[Params]
    github = "https://github.com/rwlpf"
    twitter = "https://twitter.com/SQLBobScot"
    email = "rwlp.french@gmail.com"